### PR TITLE
make it work with python3

### PR DESCRIPTION
**Pull request by iclementine**
I fork this at September 18th or so, and adapt it to work with python 3, with tensorflow 1.1

### CODE REVIEW

**Review by akjindal53244 — COMMENTED** [review]
Hi, Thanks for showing interest in my work. 

1. Current code is compatible with tf 1.2 and python 2.7
2. I will make change into apply gradient logic. Thanks for pointing it out :+1:

**Comment by iclementine** [comment]
Thanks for replying. As it is my first trial to pull a merge request, I am not sure if I've followed the github conventions. I forked it and made some changes. But I also want to keep track on your later updates.

**Comment by akjindal53244** [comment]
Hey, I am also sort of new to git. I made this repository for tracking my progress. Apart from compute gradient change, current code is updated to tf 1.2 already. I will commit this change myself since I am also not much familiar this PR concepts. I like to code in python 2.7

For now, I will close both pull requests. I will probably make a commit after little clean up of repo.

**Comment by iclementine** [comment]
thank you! happy coding!

**Pull request closed without merging**
